name: Tests
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install
        run: |
          python -m pip install flake8 pytest coverage
          python -m pip install .
      - name: pytest
        run: |
          pytest pyhms
      - name: flake8
        run: |
          flake8 pyhms
